:max_retries: 5
:schedule:
  delete_old_schedules:
    cron: '0 0 0 * * *'
    class: DeleteOldSchedulesJob
  delete_old_link_tokens:
    cron: '0 0 0 * * *'
    class: DeleteOldLinkTokensJob
  update_schedules_from_google_calendar:
    cron: '0 0 0 * * *'
    class: UpdateSchedulesFromGoogleCalendarJob